### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by eyalk11** [ZSaberLv0/ZFVimDirDiff#41] opened 2024-01-08 16:58 UTC
I strongly recommend using it, as it saves a lot of processing time. 
In Linux you usually have `md5sum` that you can introduce into diff.sh . if the hash is the same, mark it as same. 

But it is easy to implement it in python  i.e. 

```
import hashlib
file1_path = 'path/to/your/file1.txt'
file2_path = 'path/to/your/file2.txt'
def calculate_file_hash(file_path):
    with open(file_path, 'rb') as file:
        file_hash = hashlib.sha256(file.read()).hexdigest()
    return file_hash
file1_hash = calculate_file_hash(file1_path)
file2_hash = calculate_file_hash(file2_path)
```

 Or even lua maybe. 
https://github.com/kikito/md5.lua

**Comment by ZSaberLv0** [comment] 2024-01-08 21:54
seems make sense, i'll take some benchmark later

---

however, i think the main performance issue was caused by lots of `ls` and `diff` jobs on each dirs and files, maybe a better way is completely rewrite backend by python

**Comment by eyalk11** [comment] 2024-01-08 23:43
Typically not a lot of files are changes, so there is not a lot of diffs, and those that are changed, are possibly ones which interest the user.

**Comment by ZSaberLv0** [comment] 2024-01-09 03:23
after some test, `md5sum` generally cost a little more time compared to `diff`

---

as i guessed, the main performance issue was caused by lots of jobs
when comparing two files, `diff` only result to one shell command, while `md5sum` would result to two (one for each file), that suits the test result

gona working on a new python backend

**Comment by ZSaberLv0** [comment] 2024-01-09 12:30
struggled for a long time, implementing python backend is much more complex than i thought
* if the python side is single threaded, it's very complex to implement "manually update some of child dir when diff running"
* if the python side is LSP like (communicate with vim with RPC or similars), it's hard to share diff result tree between python and vim, especially when the diff tree is large, i doubt the performance would be better

---

so, for now, it seems not so necessary to involve such complex things, this issue won't be fixed for now, but pinned as a valueable issue
i have made it fully modularized to supply new backend, if anyone interested to implement the python (or others) backend, go check [apiImpl.vim](https://github.com/ZSaberLv0/ZFVimDirDiff/blob/master/plugin/apiImpl.vim)

**Comment by eyalk11** [comment] 2024-01-12 21:22
Implementing python as inline is quite easy. 

```
python3<< EOF
file1=vim.eval('variable')
... python code
EOF
```
There are also remote plugins. But it is really overkill.

**Comment by ZSaberLv0** [comment] 2024-01-15 15:30
well, that's not so easy, simply embed python does not improve performance, you need make it fully async, that's the hard way

---

anyway, i have push the branch [python_backend](https://github.com/ZSaberLv0/ZFVimDirDiff/tree/python_backend) (also keep in mind to update ZFVimJob to latest), which should improve performance from around 70 seconds to 48 seconds for my test case (around 17000 files)
the main idea is to reuse python process, and use job send instead of job start to reduce lots of job fork

code has changed a lot, please test and send feedback :)

**Closed as completed** 2024-03-18 17:15 UTC
Labels: help wanted, good first issue
